// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [
    {
      type: 'doc',
      label: 'Home',
      id: 'index',
    },
    {
      type: 'link',
      label: 'Radio',
      href: '/ac_radio',
    },
  ],
  ac_radio: [
    {
      type: 'link',
      label: 'Home',
      href: '/',
    },
    {
      type: 'autogenerated',
      dirName: 'ac_radio',
    },
  ]
};

module.exports = sidebars;
